[package]
name = "finance"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest={version="0.12.9", features=["json", "blocking"]}
ratatui="0.29"
color-eyre = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
